### ISSUE TITLE
Put it on OpenShopChannel

### ISSUE THREAD

**Issue by Gojobriel** [TheBlueOompaLoompa/flapwii-bird#1]
[Here you can publish](https://oscwii.org/publish)

**Comment by TheBlueOompaLoompa** [comment]
I'm working on it but I'm confused if I should have been sent an email by now, I haven't gotten an email yet so I'm wondering if I misspelled my email when creating the publish thing.

**Comment by TheBlueOompaLoompa** [comment]
It is now up on the osc [https://oscwii.org/library/app/flapwii](https://oscwii.org/library/app/flapwii)
